veicoli.selectByFilter = select v from Veicolo v \
join v.tipoVeicolo tipoV \
join v.categorie cat \
join v.tipoAlimentazione alim \
join v.colore col \
join v.marca marca \
left join v.macchina macchina \
left join v.moto moto \
left join v.bici bici \
where (:id is null or v.id = :id) \
and (:tipo is null or tipoV.id = :tipo) \
and (:categoria is null or cat.id = :categoria) \
and (:alimentazione is null or alim.id = :alimentazione) \
and (:colore is null or col.id = :colore) \
and (:marca is null or marca.id = :marca) \
and (:porte is null or macchina.numeroPorte = :porte) \
and (:targa is null or macchina.targa = :targa or moto.targa = :targa)

categoria.findByFilter = select c from Categorie c \
where (:id is null or c.id like :id%) 

alim.findByFilter = select a from TipoAlimentazione a \
where (:id is null or a.id like :id%) 

utente.selectByFilter = select u from Utente u \
where (:userName is NULL or u.userName like :userName%) \
and (:nome is NULL or u.nome like :nome%) \
AND (:cognome IS NULL or u.cognome Like :cognome%) \
AND (:role IS NULL OR u.role = :role)  
